### ISSUE TITLE
Scanning QR code to load private key sometimes doesn't work. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#1]
I have tested scanning a QR code to load a key, and loading the key by typing it.  It is always added to the list of names for addresses, but when I click on that name it crashes every time.  

It starts to load, I can even see my balance for just a brief moment, and then it crashes.

**Comment by LyubomirDominik** [comment]
Could not reproduce, try to reproduce  in Version 2 Build 5

**Comment by jabo38** [comment]
fixed.  problem was a bug with accounts that was fixed.
