### ISSUE TITLE
can't sign multisig transactions

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#10]
When I have made a multisig transaction and I turn on my app, I get a notice to sign that transactions, but when I click to show transactions, it doesn't show me any transactions to sign.

**Comment by jabo38** [comment]
still exists

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by jabo38** [comment]
fixed but new problem.  please see https://github.com/NewEconomyMovement/NEMiOSApp/issues/32
