### ISSUE TITLE
When in message view history view and I send a transaction, the keyboard should close

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#103]
Right now when I am responding to somebody that sent me a message and I click send the transaction goes through and I can see it in unconfirmed transactions, but at that point the keyboard should drop down.  People don't normally send two transactions in a row so there is no need to keep it open.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 17

**Comment by jabo38** [comment]
fixed
