### ISSUE TITLE
Need auto-fill address book suggestions when typing an account name

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#105]
I'm referencing issue #28 because it still isn't working for me.  

When I am in New Transaction and I want to make a new transaction and I start to type a name, I'm not getting any suggestions to pick from in a drop-down menu.

**Comment by LyubomirDominik** [comment]
Names is not supported only account addresses

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 17

**Comment by jabo38** [comment]
I see names and addresses.  That was very good.  thanks
