### ISSUE TITLE
Child account in multisig relationship doesn't always display transactions correctly

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#109]
If I make a parent/child relationship with multisig and the parent account sends transactions from the child account, the child account is having a hard time displaying messages in the conversation view.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/12793308/5307fc30-caf3-11e5-9de2-954cd04bf33b.png)

**Comment by LyubomirDominik** [comment]
Sorry but I don't understand you. Please explain more detailed.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 18

**Comment by jabo38** [comment]
fixed
