### ISSUE TITLE
app doesn't auto calculate fee and won't send transaction

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#11]
When in the dashboard there is new icon in the upper right hand corner.  I can click on it to make a new transaction.  If I enter the amount and click send, the transaction doesn't have a fee and won't go through.  I have to click on the message box, whether I am actually sending a message or not, and then click "done", at which point it auto calculates the fee and the transaction will go through.  

If I don't click on the message box, and enter my own fee manually, even a very high one much higher than is needed, the transaction doesn't go through.  

A person should always be able to edit the fee to make the fee higher.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 5

**Comment by jabo38** [comment]
fixed
