### ISSUE TITLE
shouldn't be able to enter less than 0.000001

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#110]
the smallest amount of XEM is 0.000001, but the transactions are letting people write things like 0.0000001.  That can't really happen.  The transactions are going through as okay, but really they are just sending 0 instead of 0.00000001.  So we need an error or block or something when people send less than 0.000001.  Android turns any number lower than 0.000001 to red and doesn't let a person send.  That seems fine to me.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 18

**Comment by jabo38** [comment]
fixed
