### ISSUE TITLE
extra 0 in the fee box

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#111]
![photo_2016-02-05_22-42-40](https://cloud.githubusercontent.com/assets/10395907/12847891/d2944ca8-cc59-11e5-8f72-947f692b4a6a.jpg)

The fee box adds and extra 0 after the decimal point when updating the transaction.  It then changes to no 0, but it is a bit awkward to see it come and go.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 19

**Comment by jabo38** [comment]
fixed
