### ISSUE TITLE
when I click back in export account, it takes me to enter password

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#116]
that is a really odd place to return to if pressing back.  in previous versions it didn't go to "enter password". 

Furthermore it isn't the "enter password" to create a QR.  It is the "enter password" one sees when the app has been closed and re-opened.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed
