### ISSUE TITLE
App crashes when you disable camera

### ISSUE THREAD

**Issue by boestin** [NewEconomyMovement/NEMiOSApp#12]
When opening the client for the first time, login to account, then at the bottom go to QR.  Then you go to the third tab "Scan".   The app asks for permission to use the camera. When you deny this, close the app and then want to correct it (approve the camera permission)  it crashes.
The crash occurs when the tab "Scan" is selected.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by boestin** [comment]
Retested and working.
