### ISSUE TITLE
If an account is not a multisig account, there needs to be no drop down box to select other acconts

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#120]
In the Android app if the account is not a cosigner on other accounts, then there is no dropdown option.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
there is still a dropdown menu in new transactions.

**Comment by LyubomirDominik** [comment]
Fixed in Versin 2 Build 22

**Comment by jabo38** [comment]
fixed
