### ISSUE TITLE
Get rid of extra "/" in invoice if not needed

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#121]
If there is no prefix set in invoice configuration, then there should be no forward slash before the invoice number.  If there was no postfix set in invoice configuration, there should be no forward slash after the invoice number.  

If no invoice configuration has ever been configured, then please no preloaded invoice number loaded in the message field.  

For example, please review how the Android app works in this manner and copy it.  
![image](https://cloud.githubusercontent.com/assets/10395907/12952160/d1ffeb00-d058-11e5-973f-dd649c44c407.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
still there

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 22

**Comment by jabo38** [comment]
fixed
