### ISSUE TITLE
App isn't auto-picking server

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#122]
App should try to test which server is fastest and chose that one.  But my app is always just choosing the last server that was used. 

Originally Android was testing like once every 20 seconds for the fastest server but we said it should only check at the start of the app and then every 5 minutes after that.  

Basically it is supposed to check the heart beat of the servers and connect to the fastest one.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed
