### ISSUE TITLE
entering a transaction, then closing app, then opening NEM app causes bug

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#124]
The send bar gets stuck at the top.  

![image](https://cloud.githubusercontent.com/assets/10395907/12955414/43b93a1e-d066-11e5-9f9a-46dd67107075.png)

**Comment by LyubomirDominik** [comment]
Can not reproduce in app Version 2 Build 20

**Comment by jabo38** [comment]
Will remake issue. It's a new similar big now.
