### ISSUE TITLE
Please allow importing the QR accounts from regular QR scan function

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#126]
once in the dashboard a person can press QR and then press scan, but if trying to scan an import account QR at that point a confusing error happens.  It is better to just let it import accounts from that scan too.  

Please see here for more info. https://github.com/NewEconomyMovement/NEMAndroidApp/issues/136

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed
