### ISSUE TITLE
Sending long message should make error that says the message is too long

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#128]
Right now it just says the transaction can't be sent and to check the server. An error that the message was too long would be better.

**Comment by fyahfox** [comment]
It shouldn't even try to send the transaction, when the app notices the massage is too long and therefore the whole transaction is invalid. That would lead to an unnecessary NIS request.

**Comment by LyubomirDominik** [comment]
Hi, we faced with such issues as:  documentation, NCC and NIS have some differences.

In documentation:

   Current : "Payload - Optional field in case the transaction contains a message. The payload is the actual (possibly encrypted) message data. The payload is allowed to have a maximal size of 512 bytes. Transaction validation detects if the limit is exceeded and returns an error in this case."
   Old  : "Payload - Optional field in case the transaction contains a message. The payload is the actual (possibly encrypted) message data. The payload is allowed to have a maximal size of 256 bytes. Transaction validation detects if the limit is exceeded and returns an error in this case."

NCC : 

  Cut message on 128-th byte (without any error message) even if message length was bigger than 128 bytes.

NIS :

  Allow us to send transaction with payload up to 160 bytes.

So all of this, show us different values for payload max length. What we should do?
For now in IOS I set 128 as this value works good. As NCC do.

**Comment by LyubomirDominik** [comment]
Max length = 128 
Fixed in Version 2 Build 20

**Comment by fyahfox** [comment]
Wait, NIS can do 512 bytes, but you cut it after 128? I don't understand..?

NCC is behind, so don't blindly follow NCC...

**Comment by BloodyRookie** [comment]
NIS handles a message size of up to 160 bytes.

**Comment by fyahfox** [comment]
So the mobile app should allow 160 bytes messages as a maximum as well, correct?
NCC too of course, but that is another story.

**Comment by LyubomirDominik** [comment]
Hi @BloodyRookie, nice to hear you ) 

So I researched it right. I'm happy) 

Max length = 160
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed
