### ISSUE TITLE
Can't send encrypted message to myself

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#131]
An account should be able to send an encrypted message to itself but when I try I get an error.

**Comment by LyubomirDominik** [comment]
What reason to send transactions to itself?

**Comment by jabo38** [comment]
there are some use cases where people want to store important information on the chain (like a password or key to a different account), they can then send themselves that info in an encrypted message.

**Comment by LyubomirDominik** [comment]
That message will cost them additional XEMs

**Comment by jabo38** [comment]
yes, they have to pay the fee

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed
