### ISSUE TITLE
iphone 5 display problem in conversation panel

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#132]
the send bar is covered up.  (reported by Makoto in chat)

![photo_2016-02-11_14-43-39](https://cloud.githubusercontent.com/assets/10395907/12970132/fc1e2742-d0cd-11e5-82af-4724a473af35.jpg)

**Comment by LyubomirDominik** [comment]
Makoto use  custom keyboard, it was not supported.
Fixed in Version 2 Build 20

**Comment by jabo38** [comment]
fixed
