### ISSUE TITLE
Encrypted messages in Android makes iOS crash

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#133]
I have an account in both Android and iOS NEM apps.  If I send a transaction for some XEM and an encrypted message to a third party with the Android app and then try to open that account in iOS, the app crashes.  

Testing Android 0.1.36 on LG G3 and latest iOS version on iPhone 6.

**Comment by jabo38** [comment]
I'm pretty sure this is the thing that caused my random app crashing that I reported before but wasn't reproduced.

**Comment by LyubomirDominik** [comment]
If you could not reproduce it, so how could we do it? 

We test encrypted messages:

Created by Android app and opened by IOS app :
1) From account1 to account2 = Good
2) From account1 to account1 = Normal (Says that can not decrypt, will be fixed regarding to another issue)

Created by IOS app and opened by IOS app :
1) From account1 to account2 = Good
2) From account1 to account1 = Normal (Says that can not decrypt, will be fixed regarding to another issue

No crashes.

**Comment by jabo38** [comment]
I have Account A and mix has Account B.   

I load the private key of Account A on Android and iOS.  So the same data is shown for both phones.  Normal transactions are fine.  

I send an encrypted message from my Account A on Android to Mix's account B.  I close the app, I wait a minute for the block to form.  I try to open Account A on iphone and the app crashes.

**Comment by jabo38** [comment]
here is a video https://www.dropbox.com/s/nni6t4ili7ce9e1/Video%20Feb%2011%2C%2012%2000%2047%20AM.mov?dl=0

**Comment by jabo38** [comment]
I could not reproduce in the latest versions.  Will close the issue.
