### ISSUE TITLE
Please allow editing of multisig with names like in new transactions

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#141]
it is a lot easier to edit multisig accounts if the names auto fill.

**Comment by kmiliak** [comment]
For both Android and IOS we propose to implement such version:

allow user to fill in whatever identifier of account user wants. It could be : account name, address, public key and app will recommend account witch is known for app but if user wants to add account not known for app as cosigner it will allow  to enter public key only

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 25

**Comment by jabo38** [comment]
fixed
