### ISSUE TITLE
Can't send more than 999 xem in new transaction. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#143]
If I try to send large amounts the transaction want go through

**Comment by LyubomirDominik** [comment]
Can not reproduce in Version 2 Build 25

**Comment by LyubomirDominik** [comment]
![cb7f01a8bdea42fc76b2ad1afafb803fb18c7b3a9a225575b2pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15227694/13393591/0d7ee640-deeb-11e5-8da7-64fb6e98b681.jpg)

**Comment by jabo38** [comment]
I'm on build 26 and still have the problem.

**Comment by LyubomirDominik** [comment]
please make video

**Comment by LyubomirDominik** [comment]
![f70a99c568db49c1d7bf4145e2720fb066e5d578bb5fcbdd21pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15227694/13568192/4a0beaf4-e468-11e5-970e-8972a9938e33.jpg)

**Comment by LyubomirDominik** [comment]
Fixed in version 2 build 27

**Comment by jabo38** [comment]
fixed
