### ISSUE TITLE
Enter Password --> a fail shoud show an error

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#144]
The "Enter Password" field doesnt "shake" or gives an error when someone typs a wrong password. 
And... is it possible to activate the "Accept" Button of the virtual keyboard on the right of the space bar with the same function as the "confirm" Button? This would be more like an IOS native Application.
![photo-2016-03-01-10-43-18_1268](https://cloud.githubusercontent.com/assets/17567386/13425361/80f5400e-dfa6-11e5-8789-88df9343cd9a.PNG)

**Comment by kmiliak** [comment]
IOS developer needs 1 hour to implement this enhancement

**Comment by Espo02** [comment]
I got today the Info, that the android version shows a "wrong password" with a red cross in the password box (if the password is wrong). That would be very good for the iOS Version too.

**Comment by Espo02** [comment]
The same Info funktion "wrong password" is missing, if you import a exported account by qr code where you have to enter the export password.

**Comment by jabo38** [comment]
@Espo02 it turns red now.  I think that should probably work.  What do you think?

**Comment by Espo02** [comment]
Yes, red schows the user he is wrong :+1:
