### ISSUE TITLE
Transaction page isn't viewed right after closing and coming back to app

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#146]
1) I go into conversation view. 
2) I start to type a translation. 
3) I press home button once 
4) I open any random app
5) I press home button twice and select NEM app
6) I scan my finger print 
7) I come back to the transaction and there is no keyboard.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 26

**Comment by jabo38** [comment]
it is still going on

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 27

**Comment by jabo38** [comment]
fixed
