### ISSUE TITLE
"Export Account" <-- this menu asks not a password...

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#150]
... if you reopen the app on this point.
Every mask ask the main password to open the app but not the "export Account" page. 
If the user opens the "export Account" page, close the app and switched to the app again, he must not enter the password.
![photo-2016-03-04-15-09-03_1274](https://cloud.githubusercontent.com/assets/17567386/13529491/d08711f6-e21c-11e5-92cf-22841ca18f34.PNG)

**Comment by jabo38** [comment]
if you press confirm, it uses the default password.  if you enter a new one then the QR is protected with new password.

**Comment by Espo02** [comment]
yes, ok. Thats the function of this configuration point. But what I mean is, if you stay at this point of the Software you can Close the ap and open it again AND you have not to enter the main Password which you have to enter normaly to open the account/app. You can navigat in the whole App

**Comment by fyahfox** [comment]
That is a pretty good catch. Security relevant, too. Thanks!

**Comment by Espo02** [comment]
My pleasure
Espo02: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by LyubomirDominik** [comment]
Fixed in Version 2  Build 31

**Comment by jabo38** [comment]
@Espo02  thanks for your help, the bounty was sent TX ID: 986f06c45ae63d2c9fe14c2e6440536ebb8333010b08a4816a720b2f846b76f7
