### ISSUE TITLE
Can't send any XEM!

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#151]
everytime I try to make a transaction, it will not work.  

Android is having problems too, I heard

**Comment by LyubomirDominik** [comment]
maybe there were some problems with NIS you are connecting to

**Comment by LyubomirDominik** [comment]
![f70a99c568db49c1d7bf4145e2720fb066e5d578bb5fcbdd21pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/15227694/13568147/04cfda0e-e468-11e5-829b-0441b2a45c75.jpg)

can not reproduce, need video

**Comment by jabo38** [comment]
is working in v. 2.27
