### ISSUE TITLE
Please add list of servers

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#152]
Here is the list of IPs to check with servers

37.59.43.140

52.62.133.0

54.207.48.129

52.69.252.224

104.128.226.60

54.254.215.55

193.84.22.102

52.79.74.84

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 27 (Need to reinstall app)

**Comment by jabo38** [comment]
fixed, but not working right.
