### ISSUE TITLE
Server list should only show one server

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#155]
I can only be connected to one at a time I think.  
![image](https://cloud.githubusercontent.com/assets/10395907/13571611/6c6345f6-e4b9-11e5-87e6-91d15e47204d.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 28

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
fixed
