### ISSUE TITLE
No Primary Server

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#160]
I constantly get a message "No Primary Server" and don't get my notifications for translations. The reality is I have a sever running at my house and their are a long list of running servers on true list. 

It needs to auto-pick a good one.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/13700808/9472bbf2-e7c6-11e5-9fd3-40e518e0e4b3.png)


and this one shows no response from server too.  I have tried different servers that work while I am in the app but show this message. 

![image](https://cloud.githubusercontent.com/assets/10395907/13700822/abb2e2ec-e7c6-11e5-807a-0515e78d7a15.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 30
