### ISSUE TITLE
Touch ID is sometimes fast and sometimes slow

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#162]
This isn't exactly a bug, but is something I would like to look into.  Touch ID is sometimes immediate and sometimes has a few second pause, which is actually quite a long time when you are waiting for it, and on a rare occasion doesn't come at all and the password has to be entered manually.  Please look into it and see if the performance can be more consistent.  Not sure if it is just my phone or across other phones but I guess so.  latest iOS and iphone 6.  This problem has existed for a few weeks at least.

**Comment by LyubomirDominik** [comment]
Touch ID handled by IOS system, app only know if user fail all his chances or successfully pass it.
So it is not a bug of IOS app. Try to delete your finger from settings and add new one.

**Comment by jabo38** [comment]
The Touch ID menu doesn't come up at all. I start the app and am only given a choice to use the password.

**Comment by LyubomirDominik** [comment]
Moved to issue #191
