### ISSUE TITLE
Fee does not auto adjust a second time

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#163]
If I enter a number that is big, the fee adjust to fit that number.  but if I realized I hit an extra 0 or something and the number was too big and I go back to make it a smaller amount, the fee does not auto adjust down to smallest amount.

**Comment by jabo38** [comment]
here is another example.  I enter 08.  It auto-changes to 8 which is great, but the fee doesn't change to 2.

**Comment by LyubomirDominik** [comment]
It's not a bug, app could not know if fee is custom fee entered by user or minimal fee from previous counting. App work in such way if fee is less than minimal fee it set fee equal to minimal, in other way it will show that minimal fee is N but fee is equal to old fee as it is valid fee. 
So in your example above fee text filed will be label : "Fee : (Min 2 XEM)" But fee will be equal to 8

**Comment by jabo38** [comment]
fixed
