### ISSUE TITLE
Fingerprint scanner doesn't work after app has been closed for a long time

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#165]
This has been a problem for a long time but I couldn't reproduce it reliably.  Finally I figured it out.  Touch ID doesn't work if the app have been closed for longer periods of time.  Like in my last instance it was closed a day.

**Comment by LyubomirDominik** [comment]
Fingerpass functionality is not dependent on time.
In my case I didn't use app for a month and when I opened it - everything was ok.

**Comment by LyubomirDominik** [comment]
Moved to issue #191
