### ISSUE TITLE
Fee for Transactions doesn't auto update

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#166]
I clicked around for a while in the transaction menus.  I sent the transaction but it charged me 10 XEM instead of 4 XEM.  

![image](https://cloud.githubusercontent.com/assets/10395907/14128981/c910d710-f660-11e5-86ef-d031b2ea6150.png)

**Comment by LyubomirDominik** [comment]
I check this issue.

The result : 
You send this transaction from "New Transaction" page, as only there you can set custom fee.
Also I want to mention that default fee (for 0 XEM with empty message) is 10 XEM which was set if you open and close keyboard without any changes. As was mention in previous issues if fee app calculate new fee which is less than previous calculated fee, fee will stay the same but above the fee will be hint that minimal transaction fee is _SOME_VALUE_ which will be less.

**Comment by Espo02** [comment]
If the amnout will be adjusted, the fee should be corrected to the minimum.
![photo-2016-05-29-13-44-44_1959](https://cloud.githubusercontent.com/assets/17567386/15633053/e3c27484-25a3-11e6-899c-9056bc0e5bdf.PNG)

**Comment by jabo38** [comment]
This issue isn't resolved.  When a person changes the amount the fee should automatically adjust down.  It doesn't make sense to make it adjust sometimes and sometimes not.  People don't like to pay more.  In rare case a person does want to pay more fees, they can do so via going to the fee box and entering a higher fee.  That should be the only time the transaction sends with a higher fee.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 38

**Comment by Espo02** [comment]
It works :+1:

**Comment by jabo38** [comment]
@Espo02 thanks for testing.
