### ISSUE TITLE
New threads with the first transaction still pending doesn't appear in Dashboard

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#167]
I get a fresh account I haven't ever sent to.  

I go to new transaction.  I send some XEM or message to my new friend.  

I go back to Dashboard and that transaction can't be seen.  Only once it is confirmed does it pop-up.

**Comment by fyahfox** [comment]
Yes, that will be confusing for users. Just display it as uncofirmed, but don't completely hide it.

**Comment by jabo38** [comment]
So basically when a transaction is initiated and is pending, it needs to be shown in Dashboard in someway or another.

**Comment by kmiliak** [comment]
We can show in such way:
![dashboard unconfirmed](https://cloud.githubusercontent.com/assets/15012877/14248245/285770de-fa7c-11e5-9a7b-e5b28ceafb65.jpg)


For IOS version - 1 hours, Android - 2 hours.

**Comment by jabo38** [comment]
@kmiliak please update the app to do as shown in the screen shot.  Thanks

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 34

**Comment by jabo38** [comment]
fixed
