### ISSUE TITLE
Multisig -> Sending an encrypted message brings an error

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#168]
The NEMiOSApp 2.0(31) creates an error when the user sends an encrypted message with an Multisig transaction.
If you sent with the mobile app the multisig encrypted message, the cosignator and the multisig accounts wont be loaded by the current NCC (0.6.74) Programm. It shows "Loading Balance".
Other Accounts in the same wallet are working well.

==============================

I have generated three examples on the Testnet.

NEMiOSAPP Encrypted Message Bug

Multisig Account: 	TDRIUN-UPYDNN-NBKRZ4-4WZSQM-JZL255-SYWRNR-6QKW
Private Key:		00e44c901eb83afc4a9abf865d31047af6dff89a6e64ac2244a51c37a68462312b

Cosignateur1: 		TCUVQY-7IE3DE-32WJZ3-HWWCY2-LMHFXT-FIIX2R-JZPA
Private Key:		010813ce228838e5d827bfbba72a01c77ed0f4efdafdd0ad6d12d2fccf9ca5c3

Cosignateur2: 		TCSTOW-ZMCHOE-F5BKVE-6INTUY-RXC3WJ-24YOPH-GEPY
(The Mobile Account which is still working)

After changing the Multisig Account by adding the cosignator 2 (a Mobile App Account) and making a transaction by cosignator 2 both (Multisig Account and Cosignator1) Accounts are not working in NCC 0.6.74Beta 
The Nis Service dont gives errors.
I created all transactions within 5 to 10 confirmations. 

==============================

Kind Regards from Germany
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment]
After one day all faild transactions are canceld by the system. In small tests it shows that the NCC gui isn't able to encrypt messeges as cosigner for the Multisig. The NEMiOSAPP doesn't deaktivate the encrypt Button when transaction is made with a cosinging account. <- thats the Bug

**Comment by Espo02** [comment]
After one day all faild transactions are canceld by the system. In small tests it shows that the NCC gui isn't able to encrypt messeges as cosigner for the Multisig. The NEMiOSAPP doesn't deaktivate the encrypt Button when transaction is made with a cosinging account. <- thats the Bug

**Comment by Espo02** [comment]
My writing to this Bug on https://forum.nem.io:    
Yes, I know. So the easiest way is to deaktivate the enc Button if the user takes a cosining account to make a transaction. The NCC did the same in my test :slight_smile:
    It is heavy that, if you now encrypt with a cosining Account on the iPhone that the NCC can't load the Multisig and the other cosining Account until the cosining period come to the end.

**Comment by Espo02** [comment]
![photo-2016-04-03-11-42-18_1377](https://cloud.githubusercontent.com/assets/17567386/14231801/5d0e47da-f991-11e5-910e-6b92ee808492.PNG)

**Comment by Espo02** [comment]
It is still possible to send encrypted messages from a cosinging account.
I hope that the new desktopclient will not crash like the ncc.

![enc_cosignator_message_error](https://cloud.githubusercontent.com/assets/17567386/14569142/200e9942-033d-11e6-81e1-58e95386f41c.png)

![photo-2016-04-15-19-03-07_1478](https://cloud.githubusercontent.com/assets/17567386/14569144/23b16c0a-033d-11e6-8361-b26e3a86ae6b.PNG)

**Comment by fyahfox** [comment]
Good catch! If NCC disables encryption for multisig transactions, then the app should do that as well.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 35

**Comment by jabo38** [comment]
Transaction hash: 5477d865c7a93830748f009158b6928d77682884ecae5ac919b041ea13676153

Bounty paid.
