### ISSUE TITLE
Scanning a QR for account, but forgot password.  Not way to go back or cancel. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#169]
If I get to this screen when trying to add a new account and I have the wrong password or no password, then there is no way for me to go back. I have to kill the app.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/14216921/48f9458a-f886-11e5-9aad-3061b78a8064.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 32 BETA

**Comment by jabo38** [comment]
fixed
