### ISSUE TITLE
Tapping Scan button crashes the app.

### ISSUE THREAD

**Issue by kmn** [NewEconomyMovement/NEMiOSApp#17]
Tapping Scan button crashes the app.
This happens in spite of  the rest of xem amount in my account; 
when I have 0 xem or 1000 xem, app is crashed in both case. 
 
env: iPhone 5s , iOS9.1 (13B143)

**Comment by jabo38** [comment]
I wonder if it is related to this https://github.com/NewEconomyMovement/NEMiOSApp/issues/12  

it might be something different though

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by fyahfox** [comment]
can this be closed?

**Comment by LyubomirDominik** [comment]
Please close or give new reason of issue.
