### ISSUE TITLE
Shouldn't be an auto-filled 0 in New Transaction

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#171]
It is nice when you go to New Transaction and type in an address.  The Amount box is auto-filled with a 0.   Then when I go to type in the box, it is still there.  

![image](https://cloud.githubusercontent.com/assets/10395907/14230300/eab698a4-f98b-11e5-861f-967c83dd26ae.png)

**Comment by LyubomirDominik** [comment]
Fixed i Version 2 Build 32 BETA

**Comment by jabo38** [comment]
fixed
