### ISSUE TITLE
Multisig Transactions are not being displayed properly

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#172]
This account is a signer over another account.  When a transaction goes through, shows up with the message on my Dashboard, but when I enter the conversation there is no message.  That is inconsistent.  It also looks weird to have a message conversation with no transactions.  

![image](https://cloud.githubusercontent.com/assets/10395907/14230319/6ffda552-f98c-11e5-849b-af0ce3f05cd6.png)

![image](https://cloud.githubusercontent.com/assets/10395907/14230326/9aa022bc-f98c-11e5-8455-f2da54222f85.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 33

**Comment by jabo38** [comment]
fixed
