### ISSUE TITLE
In message view we need a + and - for amounts.  

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#174]
Testing Android I noticed that there are a + and - for transactions of XEM in message view.  This helps to make things more clear. 

![image](https://cloud.githubusercontent.com/assets/10395907/14230437/5b5e94ca-f992-11e5-9cd9-4cd09b6187a9.png)

![image](https://cloud.githubusercontent.com/assets/10395907/14230439/6fc5e7a6-f992-11e5-8e6e-cc3643c481ed.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 32 BETA

**Comment by jabo38** [comment]
fixed
