### ISSUE TITLE
Dashboard of multisig transaction amount not displayed right

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#175]
Show are the screen shot of an Android phone and iOS phone of the same accounts.  

The Android phone is showing both transactions as out going which is correct.  But iOS is showing one as incoming. Not sure why.  

iOS
![image](https://cloud.githubusercontent.com/assets/10395907/14230446/efa8c092-f992-11e5-87d4-c592bbb526b8.png)

and Android 
![image](https://cloud.githubusercontent.com/assets/10395907/14230450/fc1c13ce-f992-11e5-94f5-a79a00805aed.png)

**Comment by jabo38** [comment]
I need to double check more later when I'm free. Maybe Android is wrong, and iOS is right, but clearly somewhere there is a difference and there shouldn't be.

**Comment by LyubomirDominik** [comment]
Both screens are right as second transaction is  as incoming, as outgoing. For now such transaction will be in gray color with "±".

Fixed in Version 2 Build 32 BETA

Please double check before making issue as mustfix.

**Comment by jabo38** [comment]
fixed.  now can see ±
