### ISSUE TITLE
Don't need time stamp to the seconds on the Dashboard

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#176]
Just to the minute is more simple and just fine like how Android does it. 

iOS
![image](https://cloud.githubusercontent.com/assets/10395907/14230464/5e814570-f993-11e5-975c-3598bb0b84a5.png)

Android
![image](https://cloud.githubusercontent.com/assets/10395907/14230462/4ffd0e4e-f993-11e5-8542-84e6b275369a.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 32 BETA

**Comment by jabo38** [comment]
fixed
