### ISSUE TITLE
SEND transaction button text was not translated into Spanish and probably neither in other languages too

### ISSUE THREAD

**Issue by fiazk** [NewEconomyMovement/NEMiOSApp#180]
![photo_2016-04-04_00-23-51](https://cloud.githubusercontent.com/assets/17099341/14235335/bd6eeda4-f9fb-11e5-8113-8da409e235c5.jpg)
As you can see the "SEND" button still in English. This word was translated for iOS in line 223.

Mobile: Samsung S3
Android 4.3
NEM 2.0
NEM Address if bounty is applicable: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by jabo38** [comment]
Confirmed.  I think we need a new string or change in code for this.  Elsewhere it does get translated, so that is nice.

**Comment by LyubomirDominik** [comment]
Fixed i Version 2 Build 32 BETA

String was localized, but not used by mistake.

**Comment by jabo38** [comment]
Transaction hash: 30a2c02ce207710ea0f9169039c8e4f6428b6069c098dc4a46ac56bcade958f9

Bounty paid

**Comment by jabo38** [comment]
fixed

**Comment by fiazk** [comment]
confirmed fixed
