### ISSUE TITLE
Spanish Translation Issues

### ISSUE THREAD

**Issue by fiazk** [NewEconomyMovement/NEMiOSApp#183]
All the issues have been coloured in red in the translation table. There are a few more not mentioned below that only required more space to fully display the string.

- The "Cancel" button seems to have **bold** activated
![photo_2016-04-04_00-51-22](https://cloud.githubusercontent.com/assets/17099341/14235469/9353ce8c-f9ff-11e5-946d-9ab38c52e7e1.jpg)

- In the Servers tab, instead of "Hecho" it displays "H...ho"
![photo_2016-04-04_00-55-39](https://cloud.githubusercontent.com/assets/17099341/14235488/ff61b08a-f9ff-11e5-962a-eacfd30f8273.jpg)

- Scan QR code text too long for the button size
![photo_2016-04-04_01-00-24](https://cloud.githubusercontent.com/assets/17099341/14235508/a5ac9e46-fa00-11e5-8388-289d205fac70.jpg)

- "Share Address" = "Compartir Dirección". Not enough space and there is no alternative translation
![photo_2016-04-04_01-02-50](https://cloud.githubusercontent.com/assets/17099341/14235519/fee31332-fa00-11e5-9ccc-29680b62205e.jpg)

- "Save Changes"="Guardar cambios.  Not enough space and there is no alternative translation
![photo_2016-04-04_01-04-39](https://cloud.githubusercontent.com/assets/17099341/14235525/3ea37aa2-fa01-11e5-93fd-b0f2b5c128d4.jpg)

Mobile: Samsung S3
Android 4.3
NEM 2.0

**Comment by jabo38** [comment]
thank you for reporting.  I think if there are no other options, these boxes need to be a little bigger.

**Comment by fyahfox** [comment]
In many cases it is no problem to make the textboxes/buttons bigger.

But for copy/share address, you could just use "Copy" and "Share" (not "Copy Address" and "Share Address").

**Comment by fiazk** [comment]
Cool, I will change those strings to "Copy" and "Share"

**Comment by LyubomirDominik** [comment]
When we provided you with localization files, we mention that strings length must be less or equal to original string. There is strings which could be longer than original but it's only there where we could give more space. As we mention requirements to strings, it's not a must fix issue or bug.

**Comment by fyahfox** [comment]
It simply isn't possible to translate everything with strings that are equal or less in size, so its senseless to discuss that.

And the button "Save changes" is just one example where we have the whole screen width for the button theoretically, but it is limited to a smaller width.

Either way, we have to find a solution.. If you have other ideas, please share.

**Comment by kmiliak** [comment]
Can you please check other languages if there is the same problem?
And also please provide list of screens which need enhancement (enlarge text boxes, buttons etc.)

**Comment by jabo38** [comment]
@kmiliak 

I'll try to talk to the translators and get a list so we can do it all at once.

**Comment by fiazk** [comment]
@jabo38 Nem address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by jabo38** [comment]
Transaction hash: 2af9909756db18480826c87f6abda106f9a542241de071df754dc2dd74484b75
Bounty paid.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37

**Comment by fyahfox** [comment]
@fiazk Can you please confirm that all problems in this regard are fixed? Then we can close this issue. Thank you

**Comment by jabo38** [comment]
fixed

**Comment by fiazk** [comment]
@jabo38 @fyahfox I corrected these issues from Jabo's ss it would be nice if someone sends me again with the newest version
