### ISSUE TITLE
Multisig -> Adding a new Cosinger doesn't work

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#185]
Hello
The Funktion Add Cosinger doesnt work.
You can put an address, but the green button doesnt accept, say or do anything. 
(Nor with an address with or without the minus symbol)

If you want to change the "min Cosining accounts", that works very well!

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

![photo-2016-04-04-17-29-11_1380](https://cloud.githubusercontent.com/assets/17567386/14253410/b2995654-fa8b-11e5-9284-e689a63ab1d9.PNG)

**Comment by jabo38** [comment]
Repeat of issue https://github.com/NewEconomyMovement/NEMiOSApp/issues/170
