### ISSUE TITLE
Private Key Export and then import doesnt work

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#187]
I tried to export my private key wich shows me a qr code, public key and the private key.
Then I deleted the account and Imported it with the QR Code - WORKED :+1: 
Then I deleted the account again and tried to Import the account again withe the private key. But there was one Character missing. 
It seems the the Export doesnt show the last character, becaus to import a account from NCC by private key worked for me.
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5
![not working private key](https://cloud.githubusercontent.com/assets/17567386/14274483/f8fd48ae-fb11-11e5-8bad-df3a20d81c43.PNG)
![missing character](https://cloud.githubusercontent.com/assets/17567386/14274493/01f58ca0-fb12-11e5-82bc-1927a8f1f655.PNG)
[Info Key.txt](https://github.com/NewEconomyMovement/NEMiOSApp/files/203998/Info.Key.txt)

**Comment by jabo38** [comment]
I couldn't repeat.  @Espo02 can you paste the private key in here.  I don't want to type it out manually off of the screen shot.

**Comment by Espo02** [comment]
In the file at the end of my post is the private key i wrote down from the export. 
825901d40c45f9571eae8d2d89f307aeed925614dedfbf7138bf6fd9fbb1684

**Comment by Espo02** [comment]
Ui, I tested some things. This Bug is Tricky.
This Private Key will be shown: 825901d40c45f9571eae8d2d89f307aeed925614dedfbf7138bf6fd9fbb1684
This Private Key will bei copied if you copy the whole text by system:
825901d40c45f9571eae8d2d89f307aeed925614dedfbf7138bf6fd9fbb16844

The Last Character will be copied but not shown.

**Comment by Espo02** [comment]
And on this point. If you copy the Priv key, the curser is at the top of the screen 
![photo-2016-04-05-21-53-44_1397](https://cloud.githubusercontent.com/assets/17567386/14296169/2142194a-fb79-11e5-943a-bc303f3fa961.PNG)

**Comment by jabo38** [comment]
I can confirm that this is a problem with the 5S screen and the 6 and 6 plus are unaffected.

**Comment by LyubomirDominik** [comment]
yes this issue comes up on IPhone 5 5S

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 33

**Comment by Espo02** [comment]
it works :+1:

**Comment by jabo38** [comment]
Transaction hash: c854dd3bb56ea488d2e6cff65e6c5e496f966a0d2e84f2fa03e9889b72a20093
Bounty paid.
