### ISSUE TITLE
App crashes after Account delete

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#188]
If I import a private key and I mistype a character I got a account with a balance of 0 (zero). If I open it and look to the address (and qr and so on) -> all works. But if I delete the account after that, the app crashes in 3 of 5 times.
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Espo02** [comment]
If I create a Account, export the private key, and go to the main menue to delete the account crasches the app after 3 seconds

**Comment by jabo38** [comment]
Sometimes when I delete and account (I'm not sure if it has anything to do with when/how it was added, my app is crashing too).  Hard to repeat every time.  Sometimes it works fine, sometimes it crashes.  Not sure why.

**Comment by Espo02** [comment]
On the newst Version 2.0 Build 32BETA I tried hard to get an appcrash. But the last hour and 20 times deleteng new and existing accounts the app was stable :+1:  :)

**Comment by LyubomirDominik** [comment]
Can not reproduce in Version 2 Build 33

**Comment by jabo38** [comment]
@LyubomirDominik if our apps are crashing can you get a crash report to look more into it as this is a real problem that still happens.

**Comment by jabo38** [comment]
Transaction hash:13e86480788ccc61ee0fcea2d4dd540c1ba7caac93072a9916322c94ddfc742d
Bounty paid.

**Comment by LyubomirDominik** [comment]
Try t reproduce in Version 2 Build 37

**Comment by jabo38** [comment]
@Espo02 is this still crashing for you in the latest version?

**Comment by Espo02** [comment]
no, now its stable.
