### ISSUE TITLE
scanning old QRs of private keys auto loads the password

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#19]
this is kind of a big problem. 

when I am scanning QR codes from a long time ago during the scanning process it automatically reads, knows, and auto loads the password into touch ID.  

if somebody comes across a QR code and scans it, then that means they have full access to the account.  

when I scan a QR code, it should at no time have read access to the previously paired password.  that password should have to be entered as part of the process of decrypting the QR.  Of course once it is entered once, then yes, the phone should remember it in touch ID, but that password has to come from the users brain, not the QR.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by jabo38** [comment]
It looks like this is fixed.  I just want to clarify that the QRs are encrypted in a way that no information can be gained from them without the password.  Nor can the password be guessed by anybody by scanning the QR.  Is that correct?

**Comment by LyubomirDominik** [comment]
There were no encryption in old versions, in current version it is we also fix general encryption system to be compatible with Android app

**Comment by fyahfox** [comment]
can this be closed?

**Comment by LyubomirDominik** [comment]
Please close or give new reason of issue.
