### ISSUE TITLE
Language order

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#190]
Is it possible to sort the languages bei alphabet? 
![photo-2016-04-05-13-20-41_1391](https://cloud.githubusercontent.com/assets/17567386/14292664/574078d0-fb69-11e5-990b-ab39a51f0e52.PNG)

**Comment by LyubomirDominik** [comment]
yes it is possible. Could you please show me the order you want as all languages is on different languages and I don't know exactly how they should be sorted, for example: how to sort 日本語 and English

**Comment by Espo02** [comment]
Thats a very difficult question. The only thing I have found was a ISO standard: https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes

**Comment by jabo38** [comment]
ISO standard sound good to me.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37 
New sort order: 

            "LANGUAGE_GERMAN",
            "LANGUAGE_ENGLISH",
            "LANGUAGE_SPANISH",
            "LANGUAGE_FINNISH",
            "LANGUAGE_FRENCH",
            "LANGUAGE_CROATIAN",
            "LANGUAGE_INDONESIAN",
            "LANGUAGE_ITALIAN",
            "LANGUAGE_JAPANESE",
            "LANGUAGE_KOREAN",
            "LANGUAGE_LITHUANIAN",
            "LANGUAGE_DUTCH",
            "LANGUAGE_POLISH",
            "LANGUAGE_PORTUGUESE",
            "LANGUAGE_CHINESE_SIMPLIFIED",
            "Debug"

**Comment by Espo02** [comment]
cool :+1:
