### ISSUE TITLE
Touch ID

### ISSUE THREAD

**Issue by LyubomirDominik** [NewEconomyMovement/NEMiOSApp#191]
#162 #165

**Comment by LyubomirDominik** [comment]
Please describe all issues connected to Touch ID.

**Comment by jabo38** [comment]
If I open the app and touch ID comes up, but I close the app and go to another app.  Then I come back to the NEM app and touch ID doesn't appear again.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 33

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 34

**Comment by jabo38** [comment]
fixed
