### ISSUE TITLE
small cosmetics: Return Button doesn't work at "edit Accounts"

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#193]
The Return (German: weiter) Button doesn't close the keyboard if you are ready with the Account editing. (NEMiOSAPP 2.0 Build 32Beta)
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

![photo-2016-04-08-19-52-34_1419](https://cloud.githubusercontent.com/assets/17567386/14392856/ec466ae6-fdc3-11e5-8ac1-84410453ac8e.PNG)

**Comment by jabo38** [comment]
@Espo02 can you try again on the next version?  I wasn't able to reproduce this on the current version.

**Comment by Espo02** [comment]
Yes, no problem. I'm waiting for the new version :)

**Comment by Espo02** [comment]
the "weiter" Butten still doesn't do anything there. (Build 34) 
In my opinion the keyboard sould slide down if I press the "weiter" Button

**Comment by jabo38** [comment]
Reproduced.  Needs to be fixed.

**Comment by jabo38** [comment]
Transaction hash: d4e0bf9f0e0115492aab816e0c87034ec0c7757de9ecf4b4e15320e201fa8e23

Bounty paid.

**Comment by Espo02** [comment]
The "weiter" button still doesn't work in 2.0BETA36

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37

**Comment by Espo02** [comment]
It works on my Iphone :+1:
