### ISSUE TITLE
Language file incorrect path Iphone 6 IOS 9.3.1

### ISSUE THREAD

**Issue by kauppalahti** [NewEconomyMovement/NEMiOSApp#195]
Lithuanian language file follow system language.

![lithuanian 1](https://cloud.githubusercontent.com/assets/6757822/14403190/8d2ebc6e-fe56-11e5-8466-4da4aa9d329e.png)

![lithuanian 2](https://cloud.githubusercontent.com/assets/6757822/14403193/904297fe-fe56-11e5-98cd-79ab616e9a46.png)

Kauppalahti:
NDNFA5YO3VS2TUQYBILQDORS6IXBCXOOHFWARO4W

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 33

**Comment by jabo38** [comment]
Transaction hash: 44ac4855491d3f3104eeac83b7354b527d5b58c2179b1fa76717aa19af35aafb
Bounty paid.
