### ISSUE TITLE
XEM Balance: Except English the XEM balance doesn't display the correct unit characters

### ISSUE THREAD

**Issue by fiazk** [NewEconomyMovement/NEMiOSApp#196]
XEM Balance: Except English the XEM balance doesn't display the correct unit characters i.e. instead of 2,000.50 XEM it displays 2.000,50. It seems this was fixed in the English version but not in the rest. It seems it's inconsistent through non-English languages.
![photo_2016-04-10_16-05-35](https://cloud.githubusercontent.com/assets/17099341/14410734/348993c8-ff36-11e5-8967-541d698086f4.jpg)
![photo_2016-04-10_16-05-58](https://cloud.githubusercontent.com/assets/17099341/14410735/348a2310-ff36-11e5-8eb6-a8525ae8a40a.jpg)
![photo_2016-04-10_16-05-48](https://cloud.githubusercontent.com/assets/17099341/14410736/348b9b00-ff36-11e5-9d41-fa1753e59e57.jpg)
![photo_2016-04-10_16-05-41](https://cloud.githubusercontent.com/assets/17099341/14410737/348d4798-ff36-11e5-8839-e75c7a7542c6.jpg)

Nem address: NDAZM2-KCD2XB-4Y7XMM-J5UUZ3-2ZCBHE-MHRHF4-3U3W

**Comment by Espo02** [comment]
Are you on an IPhone?
I only get dots... no comma.
![photo-2016-04-11-07-50-04_1429](https://cloud.githubusercontent.com/assets/17567386/14417887/6700556a-ffba-11e5-8a28-4054bf10884c.PNG)
![photo-2016-04-11-07-49-31_1427](https://cloud.githubusercontent.com/assets/17567386/14417893/6b1b4f38-ffba-11e5-8d74-a18b9e791c9e.PNG)

**Comment by jabo38** [comment]
@fiazk is basically saying that Spanish should use the same number convention as English.  The same is at least true for Italian too.  So both of those need to be updated.  Not sure about the other languages yet.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 33

**Comment by jabo38** [comment]
Transaction hash: 250b23104e3edd4662d35fe77c9e8cbac423d53870454080e69d57d7ccedfc0c

Bounty paid.

**Comment by fiazk** [comment]
again, @jabo38 @fyahfox can someone plz check I have no iOS device. Thanks

**Comment by Espo02** [comment]
What exactly to you want tested?
![photo-2016-06-15-08-31-39_2231](https://cloud.githubusercontent.com/assets/17567386/16070173/c7589c14-32d3-11e6-8a65-57e24af820d7.PNG)
