### ISSUE TITLE
When adding a contact to address book there is no check box to send transaction too. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#198]
I just noticed in Android that when I was adding a contact to the address book that it has a check box that a user can check that adds the address to the address book and then takes them to the new transaction panel all at one time.  

![image](https://cloud.githubusercontent.com/assets/10395907/14536496/9d92eda4-02ad-11e6-975e-96451e4a720a.png)

We talked about this before that check boxes in iOS popups don't work well, but in the export account panel we used a sliding switch.  That could be fine too.

**Comment by LyubomirDominik** [comment]
SegueToSendTransaction

**Comment by jabo38** [comment]
fixed
