### ISSUE TITLE
In New Transaction panel I can click send and send a transaction while trying to chose which multisig account to chose from 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#199]
Was trying to change accounts to send from a different account.  Switched the position of my phone and my hand hit near the send button and the transaction sent.  

We shouldn't be able to send while the choose account drop down is open and a person is choosing an  account.  

![image](https://cloud.githubusercontent.com/assets/10395907/14561989/0d6282c8-0355-11e6-8fa9-c1dabaf7aa85.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 34

**Comment by jabo38** [comment]
fixed
