### ISSUE TITLE
transactions out should be in red, transactions in and adding to the account should be in green

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#2]
![photo_2015-10-20_19-27-49](https://cloud.githubusercontent.com/assets/10395907/10604641/ad627566-7760-11e5-8f36-28eb4ced8aa6.jpg)

This is a fresh account. The balance is 10,000 XEM. There is only one transaction with this account and that was to deposit 10,000. That transaction shows up in red, not green. When people give to me, it should be a plus and green. When I give to others it should be a minus and red.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 5

**Comment by jabo38** [comment]
solved
