### ISSUE TITLE
Dropdown Menu has a bug

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#201]
The dropdown menu "at adding the multisignature" has a little bug. If you hit it, you can't close it by pushing the drop down menu because it reopen it. Normaly it should close then like on the other screens.
![photo-2016-04-15-18-51-28_1477](https://cloud.githubusercontent.com/assets/17567386/14568848/b25f6508-033b-11e6-80f7-196655b85b93.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by jabo38** [comment]
Transaction Hash: c1f2d39a4f955c39ea0396d016a97fa4c93f2eba73fc1475ddae6af793b3ab8f
Bounty paid.

**Comment by Espo02** [comment]
In 2.0BETA36 it works :+1: 
But if you want to change the selected account, you have to point two times on the drop down menue.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Bild 37 

You need to tap only once to close or open the drop down menu.

**Comment by Espo02** [comment]
Cool, now it works like a charm
