### ISSUE TITLE
Enter Password has text entered already when starting up app

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#202]
I keep on seeing ******** in the enter password field where it didn't use to be there before and makes it looks like the phone is holding the password.

**Comment by Espo02** [comment]
Please make notification if a password is wrong: 
https://github.com/NewEconomyMovement/NEMiOSApp/issues/144

**Comment by Espo02** [comment]
There is still no error on an wrong or missing password NEMiOS-2.0BETA36

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37

**Comment by Espo02** [comment]
If a password is wrong it shows red dotts. <-- Thats very good. Can you optimize it, that the dotts are cleared as son as the password field gets the focus and not when I type my first letter? 
Sorry for my alwas grumble :(

**Comment by jabo38** [comment]
original issue is solved that this card was created for so I will close it.
