### ISSUE TITLE
Crash when switching between the account menu and the account overview

### ISSUE THREAD

**Issue by Mehbsl** [NewEconomyMovement/NEMiOSApp#203]
The app crashes when you transition from the account menu which lists all available accounts to the overview screen of a specific account. The problem doesn't happen every time, but in average every 6th time.

### Steps to reproduce the crash

1. Open the application
2. Authenticate yourself
3. On the account overview page tap the back button to get back to the account menu
![account_overview](https://cloud.githubusercontent.com/assets/18571472/14673093/1e162836-06fc-11e6-9f96-83aa1c18992b.png)
4. On the account menu open the a account
![account_menu](https://cloud.githubusercontent.com/assets/18571472/14673106/2b8ffffa-06fc-11e6-8548-60a3a240649d.png)

Repeat step 3 and 4 until the app crashes. 
Following video showcases the problem on an iPhone 6s with iOS 9.3.1 (13E238) and the iOS client 2.0 (34): https://youtu.be/IKxNLUxHIR0

NEM address: NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by Espo02** [comment]
I could reproduce this bug, but it crashes only with an brand new account. If I tried it with an account which gots transactions, the app crashes not.

**Comment by Mehbsl** [comment]
I performed some transactions and tested again, the app crashes even if the account has transactions, but not as often as without performed transactions. Even with a older testnet account the app crashes, but on average only every 30th time. But even if it only crashes every 30th time the problem definitely annoys the user.

Again i made a short video showcasing the problem:
https://youtu.be/GGdPpIBoqgE

**Comment by jabo38** [comment]
Transaction hash: b59639f5d83fc7c41ef6f38171251337945555580663426e5bfbde4752990320
Bounty Paid

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37

**Comment by jabo38** [comment]
@Mehbsl is this fixed for you?

**Comment by Mehbsl** [comment]
Yes, this one is fixed.
