### ISSUE TITLE
Can't send amounts over 1000 XEM

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#204]
Every time I go to new transaction and try to enter an amount above 1000 it goes to 0.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 37

**Comment by Espo02** [comment]
I got the error with 2.0BETA37 if I want to sent something over 1000XEM or so with an unencrypted message at the first time (so my app doesn't know anything about the receiver). If it worked with a small amount, larger one works. 
Please do not say " Its a security feature, not a bug"

**Comment by jabo38** [comment]
@Espo02 You should be able to send any amount with any unencrypted message to any account.  If you can't, it is a bug.  (Encrypted messages means an account must have known public key which means the account needs 1 out going transaction)

**Comment by Espo02** [comment]
where is my issue?
![photo-2016-05-29-13-38-10_1957](https://cloud.githubusercontent.com/assets/17567386/15633016/1bf41d54-25a3-11e6-84b7-513bc4c47a85.PNG)
![photo-2016-05-29-13-38-16_1958](https://cloud.githubusercontent.com/assets/17567386/15633017/1d3077b2-25a3-11e6-85b9-9eb9b018be6f.PNG)

**Comment by LyubomirDominik** [comment]
Can't reproduce in Version 2 Build 38 

Transaction send  Success or not possible if no public key

**Comment by jabo38** [comment]
fixed
