### ISSUE TITLE
Issue in Multisig

### ISSUE THREAD

**Issue by tshe** [NewEconomyMovement/NEMiOSApp#212]
I have created two accounts;

-	tshel_bt
-	nem12  

Then from **tshel_bt** account I went to **Multisig** and added **nem12** as an **Additional Signer.**

Now my issues are;

1.	Cannot un-add the Signer
2.	‘New Transaction’ botton is missing from  **tshel_bt** account (Usually the ‘New Trasnaction' button is next to Dashboard) disallowing me to send XEM or text message from tshel_bt account. I can receive XEM. 

I hope I have been able to make you guys understand my issue. 

In case my issues are valid: this is my NB2THS-ZJRJJY-LNLD2Y-LEMBWH-Q3EZLD-MP7GPQ-QAUM for bounty ;) Thanks! 

![nem_mobile_app_test](https://cloud.githubusercontent.com/assets/19391464/15562789/fdf1293e-2334-11e6-989a-a54de76b1199.png)

**Comment by jabo38** [comment]
Hi Tshe, thank you for testing.  When you make a multisig app in NEM, you are basically making a parent(s) and child account.  You will no longer longer be able to send XEM or add/delete extra signers from the child account.  All that will have to be done from the parent account. 

In this case nem12 is the parent and has full rights over tshel_bt.

**Comment by tshe** [comment]
Hi jabo,

Thank you so much. My ignorance. I didn't know that. Ll remove the issue from GitHub.

**Comment by tshe** [comment]
Hi jabo,

I have one question regarding the Multisig. The parent and child account. Since I cannot send xem from my child account. How do I transfer the amount struck in the child account. In my case tshel_bt is the child and nem12 the parent account. I have xem left in tshel_bt account and which I want to transfer it to nem12. How do I do that. Thanks for your help. 

Best

Tshe_bt

**Comment by jabo38** [comment]
@tshe open the parent account, go to the send menu, you will see a new option to choose from accounts in the parent account.  Choose the child account and it will send from it.

**Comment by tshe** [comment]
@jabo thank you!
