### ISSUE TITLE
Create an encrypted Message as cosigner works with a trick

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#215]
If you create a new transaction with a normal account and you fill "to", "amount", "Message" and encrypt it. After that you can change the "from" account to an cosignature account. The Enc-button is still green and the message will be encrypted (But can't be encrypted from the receiver).
Happily the client doesn't crash by an not decryptable message.

The same for the "send next transaction to the same account" Screen.

![photo-2016-05-29-16-03-47_1969a](https://cloud.githubusercontent.com/assets/17567386/15633859/678e5f4a-25b7-11e6-968e-1634e35ff31e.PNG)

![photo-2016-05-29-16-03-47_1969](https://cloud.githubusercontent.com/assets/17567386/15633847/344ed81c-25b7-11e6-8ea1-892eae10a0dc.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Bounty paid. Tx hash: a78143ae55e08508c289bbc942d6e65224faadfba787b8b0ee94e0cd38222857
