### ISSUE TITLE
Providing a wrong password while adding an existing account via QR code should display an error message

### ISSUE THREAD

**Issue by Mehbsl** [NewEconomyMovement/NEMiOSApp#218]
When you scan a QR-Code to add an existing account to the application and provide a wrong password **nothing** happens. There should be an error message displayed that informs the user about the situation. The user could easily think that the application isn't working when it isn't responding to actions of the user.

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by jabo38** [comment]
confirmed.  adding an account by QR and entering a wrong password gives no indication what the user did wrong.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment]
Not working, see #242

**Comment by jabo38** [comment]
I think #242 is a little different.  Now most of the time I enter a wrong password it is red (unless 242) so I'll close this.

**Comment by jabo38** [comment]
Bounty paid. Tx hash:ac3a8add1a6439e5b4d95a2eaa713413df25843387f8936902bae1eb9975e4ac
