### ISSUE TITLE
back button should make the app go to a lower level, not go through the history

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#22]
right now the app is remembering the history of all the links clicked and going through them one by one.  actually the back button should work much simpler than that. 

Anytime I am in harvest details, map, export account, or about app and I click the back button it should always take me to the more menu.  

anytime I am in the more menu, or QR, or address book and I click the back button, it should always take me to messages.  

anytime I am in messages and click the back button, it should always take me to accounts.  

Accounts has no back button :-)

**Comment by LyubomirDominik** [comment]
Must be agreed with K.Milyak

**Comment by fyahfox** [comment]
please use the same logic as for android: https://github.com/NewEconomyMovement/NEMAndroidApp/issues/9#issuecomment-165584013

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
fixed
