### ISSUE TITLE
Scanning invoices for amounts over 1000 XEM doesn't work

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#222]
When I scan an invoice for 100 XEM, it works fine.  But if I scan for large amounts it shows up as 0.  iphone 6, latest OS and latest iOS app

**Comment by Mehbsl** [comment]
I can reproduce this bug on an iPhone 6s with iOS 9.3.2 and the NEM iOS application version 2.0 (37) - amounts over 999 XEM show up as 0.

**Comment by Espo02** [comment]
is it the same like here?
https://github.com/NewEconomyMovement/NEMiOSApp/issues/204

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 38

**Comment by jabo38** [comment]
fixed
