### ISSUE TITLE
Add account by using QR Code -> Can't scroll the popup

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#223]
The Popup on the screenshot can only be scrolled if the Keyboard is activated not if you just want to add a new address. 

![photo-2016-06-07-08-44-52_2079](https://cloud.githubusercontent.com/assets/17567386/15848408/1f88e990-2c8d-11e6-889d-37adc1b60b4f.PNG)
Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 38 
There no need to enable scroll if keyboard is closed, but full popup must be visible

**Comment by Espo02** [comment]
It works in 2 Build 38

**Comment by jabo38** [comment]
Bounty paid. Tx hash: e49d284e6594f2a4a7d72933c4fc0ce6d9e9c7594bfb4e0afe3d9f5c9893b0a6
