### ISSUE TITLE
"0" in new transaction lingers

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#224]
when I enter an amount in new transaction, the 0 stays there which technically doesn't stop the transaction and it does get removed when I click to the next line, but many people go to remove it manually which causes confusion.  It should disappear when we type as that is how pretty much every app a person uses does.  

![image](https://cloud.githubusercontent.com/assets/10395907/15985311/afe97556-3023-11e6-8a29-530cecc8de37.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment]
Issue is resolved.

**Comment by jabo38** [comment]
fixed
