### ISSUE TITLE
editing a multisig account shows a "sign transaction message" when it shouldn't

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#227]
Account A: has been turned into a multisig account.  

Accounts 1, 2, 3 are signers.  One of them makes an edit to the multisig account and adds Account 4.  

When I open Account A, it asks me if I want to sign the transaction.  This is wrong.  Account A can't sign transactions because only Accounts 1, 2, 3 can sign.  Account A has no power at all so there shouldn't be a pop-up asking for the user to sign while in Account A.  That pop-up should only be in Accounts 1, 2, 3.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2  Build 39

**Comment by jabo38** [comment]
fixed
