### ISSUE TITLE
Tapping on pencil to change account name gives no response, yet tapping on name itself works

### ISSUE THREAD

**Issue by boestin** [NewEconomyMovement/NEMiOSApp#23]
When I try to change the name of the account, there is a pencil icon. Tapping on that does not change the account name though, however it works when the name itself is tapped.

**Comment by jabo38** [comment]
So basically intuitively everyone tries to click on the pencil, not the box.  Basically, people click on the pencil and then find out that the nothing happens so they think that feature is broke.

**Comment by LyubomirDominik** [comment]
Must be agreed with K.Milyak

**Comment by fyahfox** [comment]
What else purpose does the icon have? It of course must be able to click on that...

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
Fixed
