### ISSUE TITLE
Can't send transactions from specific accounts

### ISSUE THREAD

**Issue by Mehbsl** [NewEconomyMovement/NEMiOSApp#235]
At the moment i'm not able to send transactions. It doesn't matter if i use new accounts or import some existing testnet accounts. I tested multiple versions of the application, different networks, etc. I just can't get sending transactions to work. 

It is as if the application didn't knew about the account address i'm trying to send the transaction to and therefore denies sending the transaction. I can remember that in the last days someone on the forum in the mobile app beta thread asked for some test XEM and mixmaster wasn't able to send funds because of the application saying that the addresses were invalid.

I think this isn't a coincidence - is there anybody else experiencing a similar problem?

**Edit: It seems that only specific accounts are affected. In my case testnet account 17 & 18 from the mobile app thread in our forum.**

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by Espo02** [comment]
can you paste a qrcode like my to test?
![photo-2016-06-11-21-46-17_2196](https://cloud.githubusercontent.com/assets/17567386/15987135/0dd2da78-301e-11e6-9018-7dd6c3caf5ca.JPG)

**Comment by Mehbsl** [comment]
Here is a QR code for an account i recently created.

![img_2339](https://cloud.githubusercontent.com/assets/18571472/15987162/2b6a5c72-301f-11e6-9f66-a18434247b2b.JPG)

**Comment by Espo02** [comment]
works fine with Iphone 5S and Beta38

**Comment by Mehbsl** [comment]
Okay.. Now i'm able send funds back to the account you used to send me funds. But at the same time i'm not able to send funds from the imported testnet account to an address where sending used to work.

![img_2340 png](https://cloud.githubusercontent.com/assets/18571472/15987208/e10fc9c6-3020-11e6-91e8-6469b765d26f.jpeg)

**Not working:**
![img_2341 png](https://cloud.githubusercontent.com/assets/18571472/15987209/e14137c2-3020-11e6-915a-2df614dc640d.jpeg)

Why? The network can't be the problem because i'm able to send you funds, now that i received some from you.

**Comment by Espo02** [comment]
From where do you import the testnetaccount? a normal ncc account?

**Comment by Mehbsl** [comment]
I imported a testnet account via QR code from the mobile app thread on the forum - which has to work whether someone already imported it or not.

**Comment by Espo02** [comment]
which one did you take?

**Comment by Mehbsl** [comment]
17 & 18

**Comment by Mehbsl** [comment]
Okay, sending from testnet account 20 works - the problem seems to be the testnet accounts i imported. But what could cause the error? I should be able to import and send from an already used testnet account - what am i missing?

**Comment by Espo02** [comment]
It doesnt work for me on 17 and 18, too
I don't know whats the error.

**Comment by Mehbsl** [comment]
Okay, thanks for your effort @Espo02.

**Comment by fyahfox** [comment]
It works fine on Android.
How can that be?

**Comment by LyubomirDominik** [comment]
Wow, everything must work in Version 2 Build 39

**Comment by Mehbsl** [comment]
This issue is resolved.

**Comment by jabo38** [comment]
Bounty paid. Tx hash:eb2f72d88ad47e5e5d57f84982b8c9474035f0cc861c62ad3cfd41e54a233fb7
