### ISSUE TITLE
QR Code incompatible?

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#239]
Mehbsl and I tried to import the QR-Code 17 (Password **20172017**) and that worked. But we both couldn't send xem from that account. The same error came on QR-Code 18.
fyahfox could add the QR-Code 17  AND he could send some TestXem without an error [with the AndroidApp].

See: https://github.com/NewEconomyMovement/NEMiOSApp/issues/235

We made some Experiments with the QR code 18:
![doesnt work 18](https://cloud.githubusercontent.com/assets/17567386/15987581/0d3b34e8-302d-11e6-88c3-c9b439203455.jpg)

This QR-Code can be Imported with the IOS Nem App and it shows me all the details. But I can't send some TestXem. If I now copy the private key of this "not sending" account to my clipboard and import it again (after I deleted the account) I can send some Xem without problems.

PS: If I try to open the details of the QR Code 17 the app always crashes:
![doesnt work 17](https://cloud.githubusercontent.com/assets/17567386/15987598/969b7ab8-302d-11e6-8dc6-d4565d651c0f.jpg)

**Comment by Mehbsl** [comment]
Hm, interesting.

**Comment by Mehbsl** [comment]
I did some tests:

Here i performed a transaction from a working testnet account (23) - the NIS responds with SUCCESS and therefore performing the transaction succeeds:

**Request:**
![bildschirmfoto 2016-06-12 um 15 53 43](https://cloud.githubusercontent.com/assets/18571472/15991602/9975d262-30b7-11e6-9133-3ce5dbb4d828.png)

**Response:**
![bildschirmfoto 2016-06-12 um 15 52 54](https://cloud.githubusercontent.com/assets/18571472/15991601/9941a7c6-30b7-11e6-8b5e-f7559067b47f.png)

And here i perform a transaction from the failing testnet account (18) imported via QR code:

**Request:**
![bildschirmfoto 2016-06-12 um 15 53 50](https://cloud.githubusercontent.com/assets/18571472/15991608/bb3e85ba-30b7-11e6-8498-9629aa0a9bc7.png)

**Response:**
![bildschirmfoto 2016-06-12 um 15 53 10](https://cloud.githubusercontent.com/assets/18571472/15991607/bb0864bc-30b7-11e6-8882-bf73d1114246.png)

The NIS responds with "FAILURE_SIGNATURE_NOT_VERIFIABLE" when the application performs the API call to fulfill the transaction.

**Comment by jabo38** [comment]
I also got the "Failure_Signature_Not_Verifiable" error when trying to do multisig account edit transactions.  Not sure if that is related or not.

**Comment by LyubomirDominik** [comment]
That I could do something I need next information
1) What client made that QRs (IOS, Android or Web)
2) Real private key of that accounts or at least address

**Comment by LyubomirDominik** [comment]
Never mind previous message.
QR was generated from Android (old version) or Web client 100%.
Fixed in Version 2 Build 39. Add support such QRs

**Comment by Mehbsl** [comment]
This issue is resolved - i'm able to send from testnet account 18 after i imported it via QR code.

**Comment by Espo02** [comment]
I tried it, and it works :) (BETA39)
