### ISSUE TITLE
Not possible to send small amounts of XEM, decimal not working.

### ISSUE THREAD

**Issue by boestin** [NewEconomyMovement/NEMiOSApp#24]
It is not possible to send small amount of XEM to each other.  When entering for instance 1,05 it is reset to 0.  Comma and dot are both not working.

**Comment by jabo38** [comment]
I think this might somehow be related to the issue here with QR scans too as that is also a decimal point problem. https://github.com/NewEconomyMovement/NEMiOSApp/issues/20

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by jabo38** [comment]
fixed.

@boestin can close

**Comment by boestin** [comment]
Yes, verified and working
