### ISSUE TITLE
Importing QR-Code: wrong password doesn't show it

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#240]
Iporting a private key by QR-Code doesn't show a wrong password. Can it be coloured red if its wrong?

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Mehbsl** [comment]
#218

**Comment by Espo02** [comment]
oops, I didn't see it.
Thank you Mehbsl for the Info.
