### ISSUE TITLE
Question: What causes the timedifference?

### ISSUE THREAD

**Issue by Espo02** [NewEconomyMovement/NEMiOSApp#246]
I checked my Iphone against the Atom clock www.uhrzeit.org and it's on one second the same.
But the Transactions of my phone are two minutes in the future.
Where is the mistake?

![photo-2016-06-15-08-31-39_2231](https://cloud.githubusercontent.com/assets/17567386/16070251/52a95d44-32d4-11e6-9716-41f6b353a99a.PNG)

Espo: NDEFC3-H4VAIU-FQ5GFT-IK3IJR-4DGKF7-PEQKRW-LPZ5

**Comment by Mehbsl** [comment]
I think the time gets synchronized with the NIS that you're connected to - i'm not absolutely sure though.

**Comment by jabo38** [comment]
time stamps are according to the NEM network.  if we use device time stamps, people can have really off times sometimes.  The Testnet has drifted some, but as long as everyone knows it has drifted, it is okay.  NEM is the first every decentralized time sync so this is one of the effects.  I'm not sure if the mainnet is off or not, but it is known it will drift.
