### ISSUE TITLE
App crashes when trying to create a New Account

### ISSUE THREAD

**Issue by boestin** [NewEconomyMovement/NEMiOSApp#27]
The app crashes when I try to create a new account. 

Steps to reproduce:

1. Add account
2. Tap op Scan QR
3. Go back, and tap Create New
4.  Tap on any of the textfields to make it crash

**Comment by jabo38** [comment]
Confirmed.  This crashes on my phone too.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 6

**Comment by boestin** [comment]
Retested and working properly
