### ISSUE TITLE
Need auto-fill address book suggestions when typing an account name

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#28]
When I go to New Transactions and I start to make a transaction, I have to copy and paste the person's address each time.  It would be better if there was an auto-suggest of names to pick from.

**Comment by LyubomirDominik** [comment]
It must be agreed with project manager Khrystyna Miliak

**Comment by kmiliak** [comment]
This feature depends on whether we will have separate address book, or as we have combined with phone address book. I'll list all features mentioned as we need to structure them so all parts know the extra time needed for development.

**Comment by jabo38** [comment]
yes, lets talk about it more, but generally I would say that it needs to just auto-suggest only names with NEM addresses.

**Comment by jabo38** [comment]
I am bumping this issue again.  As far as I know the address book is all done and okay.  

Here is the original screen shot in the report referencing this issue.  

![image](https://cloud.githubusercontent.com/assets/10395907/12459085/4798f8b2-bff0-11e5-80fe-b8ab34bc566c.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 14

**Comment by jabo38** [comment]
fixed
