### ISSUE TITLE
Change contact doesn't change the contact.  

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#29]
This option doesn't work.  

Also, the way this action is almost always done in any app is the text box fields show the old data.  The person erases the part they are changing and leaves the rest.  Having all three blanks empty isn't really a "change contact", that is a create new.

**Comment by LyubomirDominik** [comment]
It works good. I recheck this many times.

**Comment by jabo38** [comment]
okay, it is working now on my app. that is good.  

But it still needs to have the old data filled in the blanks when the pop-up comes.  That way the data is changed and not just reproduced in each line.

**Comment by fyahfox** [comment]
is this ok now?

**Comment by jabo38** [comment]
fixed.
