### ISSUE TITLE
Names not being displayed properly

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#30]
When a person has been added to the address book, their name should appear instead of their account number.  
![name 2](https://cloud.githubusercontent.com/assets/10395907/11210269/56369662-8d6a-11e5-9975-f79b7e160c60.png)
![name](https://cloud.githubusercontent.com/assets/10395907/11210271/59b1f3e0-8d6a-11e5-9eae-ffef136a1729.png)

**Comment by jabo38** [comment]
this is the same on multisig notifications too

**Comment by jabo38** [comment]
same problem for showing account names when choosing an account in New Transaction page to choose a different account.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
fixed
