### ISSUE TITLE
Private Key doesn't generate correct account

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#31]
I have an account  TDF64C-466C3X-3JEILJ-ABOYKQ-7S2N53-I7X4PI-BH7X
And the below is the private key:
00caa713d64ea3fcbf5c70a63ac16a4d2f49ed62394f8059f954b6920294dd6c36

The problem is when entering this key into the phone I get the account number of ​
TBT7UKZI5EQSWHCQFD3MTYTQCJBPVOJWYLLEIGRC

I tested this many times and had the same problem with other private keys too.  It is pretty important that the same private key always make the same account on every platform.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
fixed
