### ISSUE TITLE
harvest page errors. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#33]
![image](https://cloud.githubusercontent.com/assets/10395907/11303795/255c633e-8fe8-11e5-84d6-23203eee38aa.png)

This account says the delegated harvesting is locked but it is actually unlocked. 

It also only shows 25 last blocks not last 4537 blocks.

**Comment by LyubomirDominik** [comment]
1) Look here https://github.com/NewEconomyMovement/NEMAndroidApp/issues/65
2)  "last 4537 blocks." this message by design show how many blocks you harvest but we display only last 25 blocks

**Comment by jabo38** [comment]
The Android App says "Last 25 Harvested Blocks" from what I can tell.  

I think if you only show the last 25 then it should say "Last 25 Harvested Blocks" at the top of that section.

**Comment by LyubomirDominik** [comment]
Okay, if you want I'll make it)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 9

**Comment by jabo38** [comment]
Great thanks.  One more small thing.  

Last 25 Harvested Block(-s) -> Last 25 harvested Blocks
