### ISSUE TITLE
New transaction account number can't send with dashes

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#37]
most of the time when people post their address they post it with dashes in a form like this TCJGF6-W4RPIL-SQFB64-F5SRUI-HHQF74-JL4ZU5-GIOT

but if I copy and paste that into the new transaction page, it will show an error.  it will only work if I format out the dashes like this TCJGF6W4RPILSQFB64F5SRUIHHQF74JL4ZU5GIOT.  

We need the app to recognize both format types.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
fixed
