### ISSUE TITLE
touch ID doesn't work when starting to send a transaction from the Address Book

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#4]
I can select a person's name in address book and it asks me if I want to send to them.  I click "send message" and the I am prompted to scan my finger print and/or enter my password.  When I try, it doesn't work and I am just asked again to scan or enter password.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 5

**Comment by jabo38** [comment]
fixed
