### ISSUE TITLE
importing account with wrong password shouldn't be possible

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#40]
Here is a QR 
![image](https://cloud.githubusercontent.com/assets/10395907/12091615/85cb1686-b33b-11e5-8567-cbb78ef7ca7a.png)

The password is asdfgh but when I scan it and enter a wrong password it adds that account to my phone and then when I try to open it, the app crashes. 

Ideally when a person tries to add an account and they enter the password incorrectly, then an error should tell them the password was incorrect, not add that account to the phone.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 10

**Comment by jabo38** [comment]
fixed
