### ISSUE TITLE
Private Key -> Public Key in Export Account

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#41]
The second section labeled "Private Key" should be labeled "Public Key".  

![image](https://cloud.githubusercontent.com/assets/10395907/12092078/4b6c64a6-b33e-11e5-9a08-8ad663269728.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 9

**Comment by jabo38** [comment]
fixed

But we still might need to adjust this page a little.  it is hard now to send the encrypted QR without exposing the unencrypted Private Key.  I'll need to discuss this with Mix and Lon and here their thoughts.
