### ISSUE TITLE
when I chose a contact the only option is to "send message" 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#42]
when I click a contact in address book a pop-up comes up and has a button to "send message".  But if I don't want to send a message, then what do I do?  

Right now the "Send Message" button also doesn't actually work.  

I am guessing that when I click outside of the pop-up then the pop-up closes, or alternatively it just loads directly to the New Transaction page.

**Comment by LyubomirDominik** [comment]
By design, there is close button in the top-right corner
https://drive.google.com/open?id=0B-3myDNfWMs2NTRIdnpHVWhaQXc

Regarding to "Send message" button -> Fixed in Version 2 Build 9

**Comment by jabo38** [comment]
wow, you are correct.  there is an "x" there.  the whole time I have tested the app, I hadn't ever seen it as it always blended into that background.  I am not sure how I ever missed that.  I need to discuss this with Mix.  maybe it should be a different color or something.
