### ISSUE TITLE
When I click Export Account the shortcut menu briefly appears but then goes away

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#44]
During the part where I enter my password, I can see the short cut bar, but then when Export Account comes it is not there.  That is a bit odd from a user experience perspective.  Also, that bar isn't functional in anyway even when it is there.

**Comment by jabo38** [comment]
Export account is not a part of messages, or any of the shortcut menus at the bottom, so that whole bar needs to be deleted.  

![image](https://cloud.githubusercontent.com/assets/10395907/12409520/355da924-beae-11e5-88a7-cda904e6aadb.png)

**Comment by kmiliak** [comment]
Can developer highlight More button (not messages) instead of deleting bar?

**Comment by fyahfox** [comment]
please just do it like android, that is perfect

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed
