### ISSUE TITLE
When keyboard is open and I switch panels the keyboard stays open 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#46]
This happens in a couple of instances.  Like if I am in edit multisig and have the keyboard up, then I click the back menu, the keyboard stays stuck open.  

Other times like if I am in the New Transaction panel and go back the keyboard closes automatically like it should.

**Comment by LyubomirDominik** [comment]
Can't reproduce. Try to reproduce Version 2 Build 10
