### ISSUE TITLE
Account History still comes up

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#47]
Sometimes when I am going back and forth through More Menu items and then I click the back button, it takes me to the "account history" panel.

**Comment by jabo38** [comment]
Also, I am noticing that the back button in the More menu sometimes works via chronological history instead of the map from Mixmaster.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 12

**Comment by jabo38** [comment]
haven't seen that error in a while.  Will close.
