### ISSUE TITLE
can't edit name of account.  

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#5]
when I am in the accounts list page, I can press edit and delete an account just fine, but if I press on the green pencil to edit the name, it doesn't work.  I also can't edit the name of the account in the my info section after clicking the QR button.

**Comment by LyubomirDominik** [comment]
In accont page you could only to delete account, by design editing account name is in profile page.
Regarding to QR page changing account name change it only on QR.

**Comment by jabo38** [comment]
I tested changing name in Profile page and it works well, but..... now we will delete the profile page in the next build, so I'm guessing now the only place to put change name is on the accounts list page.  It would be nice then when a person clicked on the green pencil then the pop-up comes to change the name, just like it is now in profile page.  that ability to change name is important.

**Comment by LyubomirDominik** [comment]
It must be agreed with project manager Khrystyna Miliak

**Comment by LyubomirDominik** [comment]
Must be agreed with K.Milyak

**Comment by fyahfox** [comment]
agreed, account renaming is needed and the only place where it makes sense it the account list, where can edit/delete accounts...

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
fixed
