### ISSUE TITLE
ADD_SERVER -> Add Server

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#51]
Also Add account -> Add Account

Add Contact is fine, but on all three of these can you please put a space before the "Add" and after the plus sign.

**Comment by jabo38** [comment]
"Add aditional signer" (spelling mistake) should be "Add Additional Signer" in the Multisig Panel

**Comment by LyubomirDominik** [comment]
Don't worry about this, such kind of issues you can fix by yourself. This texts are from localization. So when localization file will be agreed, you will be able to fix style or text the way you want.
For example:  in localization file we have "SOME_TEXT" = "Some text";  so at screen you will see "Some text", but you will be able to do whatever you want with this. Let's say we want to change text and style so we easily change that string to "SOME_TEXT" = "Some white Rabbit want tO EaT";

**Comment by jabo38** [comment]
Okay, thanks. Makes sense
