### ISSUE TITLE
Green pencil in My Info edit My Name section doesn't work.  

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#52]
When I click on the name, I can edit it, but clicking on the pencil needs to be able to do that too as that is the reason for it to be there.

**Comment by LyubomirDominik** [comment]
this pencil is just image and hint for users so they know that this field is editable.

**Comment by jabo38** [comment]
fixed.  but please look over other places where this problem is repeated too throughout the app.
