### ISSUE TITLE
add "display private key" at "export account" screen

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMiOSApp#61]
we postponed this issue because we had to think about it more, but we found a good solution now:
just add a button "Display private key" to the "export account" screen (after the user decided to use wallet password or custom), below the QR picture. If user clicks on that button, a warning is displayed, because displaying the priv key is a security issue and user should be warned/aware.
the exact wording for that warning im not sure about, but it should be clear and short.

edit:
the exact way on how to implement the "display priv key" feature was describe by jeff on trello.

**Comment by jabo38** [comment]
The following should be the warning message before accessing the private key.  It need not be displayed when shown the QR as that is password protected.  

Warning: It is essential to understand that the private key is the most important and sensitive part of your account information. **Whoever has knowledge of a private key has full control over the associated funds and assets.**  It is important for restoring your account so you should never lose it, but also keep it top secret.

**Comment by fyahfox** [comment]
Yes, and then there should be "I understand" or "Cancel" buttons.

**Comment by kmiliak** [comment]
I would like to inform that this is new feature and requires 2 extra hours for developer

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 12

**Comment by jabo38** [comment]
It still needs a way to copy private key like android does, and would benefit from a check box on the password pop-up to use default password like Android does.

**Comment by jabo38** [comment]
Edit: way is there but hard to know.  will make new issue.
