### ISSUE TITLE
One password for the wallet -> Access to all containing accounts

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMiOSApp#62]
Please make all accounts accessible after the user entered the password at app start (take a look at Android version).

People have their own phone, nobody is seriously going to use a shared phone for a NEM account.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 11

**Comment by jabo38** [comment]
fixed

**Comment by jabo38** [comment]
Opening this issue again because it seems like it has reverted?? Not sure.  

Anyway, the way Android does it is that the app asks you for you password at the start of using the app, and then doesn't ask anymore after that.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 17

**Comment by jabo38** [comment]
fixed
