### ISSUE TITLE
when choosing primary account, clicking on button doesn't work

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#63]
it is easy to change names now and generally the feature works nice but when I click on the button, nothing happens.  Clicking on the name works, but most people don't click on text, they click on the button because on a computer you would normally drag the mouse to the button and click there.

**Comment by LyubomirDominik** [comment]
Fixed inVersion 2 Bild 12

**Comment by jabo38** [comment]
fixed
