### ISSUE TITLE
multisig needs a way to edit the number of cosigners. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#67]
right now the app assumes n of n cosigners, but NEM is m of n and they users need a way to adjust that.  please see the original mock up panel.

**Comment by LyubomirDominik** [comment]
Must be agree with K.Milyak

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 12

**Comment by jabo38** [comment]
I wasn't clear enough I think.  Basically NEM has M of N. that means we might have 5 signers on an account but for any transaction to go through it doesn't always need all 5.  If we set the minimum number of cosigners to 3, then only 3 of 5 need to sign.  We need a way to change this up or down as it has to be editable.  

![image](https://cloud.githubusercontent.com/assets/10395907/12396078/cc31d3ae-be48-11e5-8b0e-7d3bd58979c9.png)

**Comment by jabo38** [comment]
I have noticed that once I am adding or deleting a signer, I can edit the number of cosigners, but that won't exactly work formatted like that.  

Sometimes editing the number of cosigners is in itself the only thing I want to do; in that I don't want to add anybody, nor delete them, just change the number of signers.

**Comment by LyubomirDominik** [comment]
Fixed i Version 2 Build 14

**Comment by jabo38** [comment]
fixed, but there is a different bug.  will make a new issue
