### ISSUE TITLE
when sliding open notification, it doesn't actually take me to that account or transaction

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#68]
it is nice that the notifications open the app, but they really should take a person to the messages panel in that account, not just open the app.

**Comment by LyubomirDominik** [comment]
Must be agreed with K. Milyak

**Comment by kmiliak** [comment]
We've not discussed if we will take user to particular screen, you've told us about notifications and when they should be shown. 
So if you want to add this feature both developers will need 8 hours for this.
