### ISSUE TITLE
Make background color of Dashboard white (like Android) 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#69]
I am testing the apps to get them similar.  I noticed that that background of Dashboard on Android is all white, which is much closer to my original mock-up in the app report.  If you can, please make it like Android.  

![image](https://cloud.githubusercontent.com/assets/10395907/12377893/e682b2c0-bd6f-11e5-91aa-5de666f26547.png)

**Comment by jabo38** [comment]
Even better would be to add lines like the original mock-up, but I guess its not necessary.  
![image](https://cloud.githubusercontent.com/assets/10395907/12377898/2dc0ef44-bd70-11e5-80e5-5f3191efbb1d.png)

**Comment by jabo38** [comment]
Please see https://github.com/NewEconomyMovement/NEMAndroidApp/issues/75 for collaboration with Android Dev.

**Comment by kmiliak** [comment]
Developers just checked the colors of background and they have the same color

**Comment by fyahfox** [comment]
@jabo38 Do you mean the gray background?
I think it would be better if Android and iOs look as similar as possible, but I don't have a strong opinion on which is better. The bubble style probably takes more room, so I guess the gray lines (Android) are better?

![photo_2016-01-19_18-32-21](https://cloud.githubusercontent.com/assets/6625264/12426651/0b652e4e-bedb-11e5-9deb-45451716b2d0.jpg)
