### ISSUE TITLE
Amound -> Amount

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#7]
when replying to a message the field "Amount" is misspelled.

**Comment by LyubomirDominik** [comment]
Not clear, could you provide screen?

**Comment by jabo38** [comment]
Sure.  It is actually a bit weird.  When clicking reply to a normal account it is fine.  When clicking reply to a multisig account it is misspelled.  

![photo_2015-10-23_18-28-12](https://cloud.githubusercontent.com/assets/10395907/10689122/da5e93e2-79b3-11e5-994b-f930173303d0.jpg)

![photo_2015-10-23_18-28-36](https://cloud.githubusercontent.com/assets/10395907/10689134/e6bf50ea-79b3-11e5-86e2-03353397ca79.jpg)

**Comment by jabo38** [comment]
error is still there

**Comment by LyubomirDominik** [comment]
Thanks, now I understand the issue) 
Fixed in Version 2 Build 6

**Comment by jabo38** [comment]
fixed
