### ISSUE TITLE
About Section in Configurations

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#71]
Android has put the About section in Configurations instead of more menu, but Configurations is actually a better place, so please stick it there to bring the apps together.  

![image](https://cloud.githubusercontent.com/assets/10395907/12377919/52efcfe6-bd71-11e5-82ed-b67dfb405bfb.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 12

**Comment by jabo38** [comment]
fixed
