### ISSUE TITLE
Invoice Format

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#72]
The Android version and iOS versions are different for invoice.  The Android system is really good.  

The invoice number is positioned in between the pre and post settings and there is a way to preset a message that starts each message field.  

![image](https://cloud.githubusercontent.com/assets/10395907/12377924/a869d606-bd71-11e5-8fbd-dc47c31c6d89.png)

(I have filled in the pre section with "pre" and the post with "post" so it would be clear on the invoice.  And have written a message as "my store) 

![image](https://cloud.githubusercontent.com/assets/10395907/12377931/b7500730-bd71-11e5-9b9a-bc46032de0ea.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 12

**Comment by jabo38** [comment]
made a new issue
