### ISSUE TITLE
Export Account and Show Private Key

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#73]
The Android Export account and Share Private Key system can work.  

When a person goes into more menu and clicks export account, they get a pop-up to set password or used default one.  Next they will see the QR and two buttons.  One for Share and one for Private Key.  

When selecting Private Key a pop-up message with a warning appears.  After accepting the private key is shown and a person can copy some or all of it by holding down on it.  

![image](https://cloud.githubusercontent.com/assets/10395907/12377978/ed1207aa-bd72-11e5-95be-24327fe648ee.png)

![image](https://cloud.githubusercontent.com/assets/10395907/12377980/f4fc054c-bd72-11e5-89e9-fe5c1dd1a52f.png)

![image](https://cloud.githubusercontent.com/assets/10395907/12377983/fb3de7ae-bd72-11e5-952c-7d631ee8c26d.png)

![image](https://cloud.githubusercontent.com/assets/10395907/12377985/0088b630-bd73-11e5-8e40-3edced9757b6.png)

**Comment by LyubomirDominik** [comment]
fixed in Version 2 Build 12

**Comment by jabo38** [comment]
fixed
