### ISSUE TITLE
Space on Dashboard in between Search Bar and Account Name and Balance Bar

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#74]
There is a grey space that is just sitting there and not doing anything.  The search bar should really sit flush against the top.  

![image](https://cloud.githubusercontent.com/assets/10395907/12378032/93724082-bd74-11e5-93f2-101f1f9a5f47.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 12

**Comment by jabo38** [comment]
fixed
