### ISSUE TITLE
Open space in More menu at top

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#76]
There is a bar of extra space at the top of More menu.  Not a big deal but it looks a bit funny.  

![image](https://cloud.githubusercontent.com/assets/10395907/12396548/5bbae3ce-be4b-11e5-83d6-37916cf8c2c7.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed
