### ISSUE TITLE
Switch Account in More Menu

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#77]
Now that I am testing Android, I noticed it has "Switch Account" in More menu.  That is basically a shortcut that takes the app back to the accounts panel.

**Comment by fyahfox** [comment]
for me this is not important to have it or not, but it should be the same in both apps of course...

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed
