### ISSUE TITLE
Can't see the "copied" message on export accounts. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#78]
Right now I have to hold down a long time.  I should be able to hold down the normal time for a copy/paste type menu.  Also, the message that shows that the key has been copied is very small and covered up by my thumb.  (I actually tried many times thinking it should have been there and couldn't find it until Domonik told me.)  

Such messages need to be seen easily.  So for instance a normal sized message comes up above my thumb and says "Copied Private Key" and stays for a little while.  

For Public Key then it would say, "Copied Public Key".

**Comment by fyahfox** [comment]
can you show us a screenshot with the too small message?

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed
