### ISSUE TITLE
Message field in Invoice Edit

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#79]
I talked to Lon.  He wants iOS and Android to both have the same functionality for editing invoices.  

Android has a field to enter "message" and iOS doesn't.  Technically, I think users could just make the postfix field longer with a preset message but that is confusing to users.  

They don't have to always look exactly the same, but the same options need be there.  

In the message field below, I have written in "my store".  

Please make sure that the final formatting is the same too.  So like for instance the ":" separates the invoice and the message. 

![image](https://cloud.githubusercontent.com/assets/10395907/12408915/9126b42c-bea8-11e5-93fb-ad4169751ec8.png)

**Comment by fyahfox** [comment]
generally the apps should behave and look as similar as possible... please iOs devs, talk to android devs and the other way round.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed
