### ISSUE TITLE
Some things are enabled yet.  

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#8]
Encrypted message, Hex messaging, the more menu, the configuration menu are all not enabled.

**Comment by jabo38** [comment]
please hold on implementing encrypted messaging and hex while we discuss it.  encrypted messaging is probably best only implemented in the new transaction page and not the quick reply page. Hex probably doesn't need to be shown at all.

**Comment by LyubomirDominik** [comment]
OK, Must be agreed with K.Milyak

**Comment by fyahfox** [comment]
hex is not needed in the app

encrypted messaging should work though. so what is the current state here?

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 8

**Comment by jabo38** [comment]
encrypted messaging works
