### ISSUE TITLE
buttons on selecting time for notifications don't work properly

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#80]
when I change time for notifications and I press on the buttons, it just grays out the line.  Pressing the time works fine, but pressing buttons should work too.  

![image](https://cloud.githubusercontent.com/assets/10395907/12408977/2b95802e-bea9-11e5-9de7-01c2e25ec5c7.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version  2 Build 13

**Comment by jabo38** [comment]
fixed
