### ISSUE TITLE
Need a drop down arrow next to account to indicate when there is a multisig account

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#82]
When there is no multisig account, it is okay to not have an arrow, but when there is a multisig account, there needs to be an arrow to indicate that there are other accounts to chose from.  Without an arrow, it will be hard for new users to discover that they can now send from more than one account.  

![image](https://cloud.githubusercontent.com/assets/10395907/12409838/61c22cf8-beb1-11e5-85d3-8cd791df3d57.png)

**Comment by fyahfox** [comment]
If there is no arrow, how can a user initiate from another account at all?

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 13

**Comment by jabo38** [comment]
fixed
