### ISSUE TITLE
color adjustment

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMiOSApp#84]
Originally @jabo38 and me made a color schema which should be used. Somehow it was not done like that. Both Android and iOs are not exactly using the colors we picked.

To speed things up, @jabo38 and me agreed on only adjusting iOs and leave Android as is, because it is really close and we are ok with that.

I hope I labeled everything what you need. Otherwise please speak to the Android devs or ask here:
![colors](https://cloud.githubusercontent.com/assets/6625264/12428625/f5a7949c-bee5-11e5-97bd-8a5352c6395c.png)

**Comment by kmiliak** [comment]
Here are color scheme we use (that was provided by Jeff in mockups):

<color name="official_green">#41ce7b</color>
 <color name="official_orange">#dfa82f</color>
 <color name="official_gray">#8e8e8e</color>

One difference was in IOS, developers used standard grey for Unconfirmed transactions, but he already changed it to 8e8e8e.

**Comment by fyahfox** [comment]
Why do we not see these color codes in the screenshot then? It was sent uncompressed from the iPhone to me...

**Comment by kmiliak** [comment]
Here is code part Android developer showed me:
<color name="official_green">#41ce7b</color>
 <color name="official_orange">#dfa82f</color>
 <color name="official_gray">#8e8e8e</color>

And we've checked with IOS developer, also the same colors. He had some difference, but fixed

**Comment by fyahfox** [comment]
I don't understand why I dont see those colors then.
Any idea? Did you check on your phone? - make a screenshot, send it uncompressed to your computer and get the color codes.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 14

**Comment by jabo38** [comment]
fixed
