### ISSUE TITLE
Need a confirmation message before finally deleting account, contact or server

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#86]
If I am in the Accounts panel and I press edit, and then I press a red X and account is deleted.  It is very important to have a second tier confirmation.  

So for instance the way that multisig goes about deleting an account is quite nice because there is a 2nd layer to the delete called "save changes".  It doesn't have to be exactly like how multisig is done, but there needs to be something. 

Android has a little "undo delete" bar that comes up, and that would be acceptable too.    

The normal way in iOS though is pop-ups.  I suggest that a pop-up message states "Are you sure you want to delete _______ account?"  or something like that.  And then they click okay.  

The reason is somebody might have ten thousand dollars in this account and if there finger slips, they will have just lost it.  For the address book contact delete, or server delete it isn't a big deal, but it would be nice standardize the behavior.  But for deleting an account, it is an absolute must.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 14

**Comment by jabo38** [comment]
fixed
