### ISSUE TITLE
More Menu items don't have navigation bar sticked at bottom.

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#89]
In testing the Android App I noticed that the navigation bar is sticky at the bottom of all the More menu sub-menus.  We need to make the apps mostly the same with some design like that.  I looked back at the panels and it was in all the mock-ups so I think it is better to add them in iOS.  

I noticed the More menu isn't in green but always grey, so better to keep it like that.  Technically they aren't in the More Menu I guess so that is fine.

**Comment by kmiliak** [comment]
Developer has added bar to screens you've asked, but on Export account it covers Private key. 
To add scroll to this screen will take some tine, as developer will need to convert this screen again. 
What would you say, if we will take away the bar from this page?

**Comment by jabo38** [comment]
Okay, in that case just take away the bar. I know everyone wants to get it done. :-)

**Comment by LyubomirDominik** [comment]
Fixed i Version 2 Build 14

**Comment by jabo38** [comment]
fixed

**Comment by fyahfox** [comment]
Android had the same issue and Android dev just made the export account view scrollable.
It would be nice if both apps look the same.
