### ISSUE TITLE
share with email title

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#9]
![photo_2015-10-21_12-05-35](https://cloud.githubusercontent.com/assets/10395907/10626645/0e913f1c-77ec-11e5-9209-ada93ef03e1e.jpg)

When I go to share via email, that top of the NEM IOS at the top and then followed by Knicht.  Not sure what KNIECHT means

**Comment by LyubomirDominik** [comment]
It's localization bug, that string is from ukrainian localisation)

**Comment by LyubomirDominik** [comment]
Fixed

**Comment by jabo38** [comment]
fixed
