### ISSUE TITLE
Copy QR button doesn't copy QR

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#91]
When I go to My Info, there is a Copy QR button but that doesn't actually copy the QR.  There is a way to actually copy the QR but I guess it takes a lot of work to enable that option because you have to add support for a more serious share/copy menu. 

I am suggesting that it is changed to a "Save QR" button.  When a person clicks on that button a pop-up message will say "Save to Camera Roll".  At that point a person can go into Photos and then press copy and then they can paste the QR anywhere they want.  It is kind of a pain, but it would work.  

The same "Copy QR" button also exists in My Invoices, so it should be changed to "Save QR" too.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 15

**Comment by jabo38** [comment]
fixed
