### ISSUE TITLE
NEM icons in Address book don't slide out correctly

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#92]
If I scroll slowly in address book the NEM icons slide away quickly, but if I go fast they appear in places they aren't suppose to and then slide out.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/12530162/8bf02326-c218-11e5-9e1a-6a241c3bf2e9.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 15

**Comment by jabo38** [comment]
fixed
