### ISSUE TITLE
App crashes when turning an account in to multisig. 

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#94]
Made a fresh account. Tried to turn it into a multisig account but the app crashes. I enter the public address of the app I would like to make a signer and click "add" and then it crashes.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 15

**Comment by jabo38** [comment]
Still crashing for me in Version 2 Build 15

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 17

**Comment by jabo38** [comment]
fixed, but needs more testing later
