### ISSUE TITLE
Displaying of Decimal Points

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/NEMiOSApp#95]
iOS and Android are doing this a little bit differently.  iOS is mostly okay. 

Here is the cross issue https://github.com/NewEconomyMovement/NEMAndroidApp/issues/88

Sometims iOS shows a decimal place when not needed.  So instead of saying 39.0 XEM, it should just say 39 XEM.  The rest of the formatting is okay with larger numbers of XEM.  

But with 0.000001 - 0.000099 XEM it is being displayed in scientific notation.  It would be better to write it is plain form if possible.   

So for this example, the best option would be:
Only display those decimal places that exist.
Example:
504 XEM
252.1 XEM
23957.0001 XEM
0.000001 XEM
etc

![image](https://cloud.githubusercontent.com/assets/10395907/12534973/8b4a371c-c2b4-11e5-8669-3d7283c3aa33.png)

![image](https://cloud.githubusercontent.com/assets/10395907/12534982/fb896d7c-c2b4-11e5-9784-60a79a39f554.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 15

**Comment by jabo38** [comment]
Issue was fixed in message history view but not in Dashboard.

**Comment by jabo38** [comment]
![image](https://cloud.githubusercontent.com/assets/10395907/12754413/776d16ae-ca0e-11e5-8b79-80a332127c86.png)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 17

**Comment by jabo38** [comment]
![os](https://cloud.githubusercontent.com/assets/10395907/12788222/1ba59d40-cadc-11e5-8aee-b9122a3efc71.jpg)


Still that extra 0 is popping up in other places.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 18

**Comment by jabo38** [comment]
fixed
