### ISSUE TITLE
Display delegated account(!) at harvest info (only if delegated harvesting is unlocked/activated)

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMiOSApp#96]
i think we had a misunderstanding here. it is of no help if the app calculates a random account and displays it as delegated account, because the app is not able to unlock delegated harvesting. this has to be done via NCC/lightwallet.

so until we have that feature (which wont happen too soon) the app should just check the network if delegated harvesting was unlocked (activated) already, and if so, display the delegated address, not priv or pub key.

**Comment by LyubomirDominik** [comment]
BloodyRookie:
"@lyubomirdominik in NCC, when you create an account, NCC secretly creates another random account and uses that as the delegated account. That is why you can let the UI show the delegated private key for an account. But that is NCC specific. So on a mobile phone you could just do the same, if someone creates an account, just create a second acccount and store both somewhere (and keep the relation of those two keys).
But you could just do it another way like saying "the delegated private key of an account is the hash of the original private key". This would be just fine too.

Now you are probably thinking "when importing an existing account (which was created in NCC), the delegated key we create on the mobile device will be incompatible to the delegated key created in NCC". That is true. And if you import a key into NCC two times (in different wallets) it will create two different delegated keys too. That is the downside of how we handle delegated keys.

Aside from that, I don't think there is an API for discovering the delegated key for an account. Even if the delegated key is published via an importance transaction, i don't think we currently have an api request to fetch the delegated key for that account.

Hope the explanation helps."

I did as BloodyRookie said, so you really want to hide it ?

**Comment by fyahfox** [comment]
@BloodyRookie probably thought that the mobile app was able to unlock (activate) delegated harvesting. But as long as this is not the case, the delegated keys or address which are created randomly by the app can't be used for anything. Or what do you have in mind? Maybe I am missing something.

That's why until then we could have the currently used delegated address, but I am not even sure if this is of any use. And if it is not, then we should not display any key or address, but just display the state of delegated harvesting (locked or unlocked).

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 15

**Comment by fyahfox** [comment]
we agreed on hiding it, until the app is able to unlock delegated harvesting.

the state will be displayed though.

**Comment by jabo38** [comment]
fixed
