### ISSUE TITLE
Export account: Use application password / enter new password

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMiOSApp#97]
v 2.0 (build 14)

When you export an account, a popup message is displayed with a textbox that you can either leave empty (use application password) or fill out (then this will be used as export password).

The logic is the same as in the Android version, but using a checkbox (Android) is better.
Again, we want the apps to look as similar as possible, so please implement the checkbox logic for iOS as well.

![photo_2016-01-26_11-40-45](https://cloud.githubusercontent.com/assets/6625264/12578523/ac224eac-c421-11e5-9681-eb6886726778.jpg)
![photo_2016-01-26_11-40-36](https://cloud.githubusercontent.com/assets/6625264/12578524/ae080e1e-c421-11e5-9456-2a8e3bf8e9a1.jpg)

**Comment by kmiliak** [comment]
We can do the check for IOS version, but the thing is that this check is standard Android design, wouldn't it be right in terms of design to use standard check from Android for IOS?
As an option, we can use IOS switcher so the design will be more native for IOS app.

What do you think?

**Comment by jabo38** [comment]
Yes. I agree with Khrystyna.  Actually check boxes in iOS exist but are very rare.  What is normally used is this.  
![image](https://cloud.githubusercontent.com/assets/10395907/12614917/f7952376-c545-11e5-8c86-a606d8678779.png)

I think that is what Khrystyna is calling a switcher.  So if the dev would make that, that would be great.

**Comment by fyahfox** [comment]
Sure, any boolean switch is fine if that is standard for iOS.
But the logic should be the same. Meaning: If option "Use application password" is selected (by android checkbox or iOS switch or whatever) then there should be no textbox, but if it is not selected then a textbox should appear where the user can enter a custom password.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 16

**Comment by jabo38** [comment]
looks good.  thanks
