### ISSUE TITLE
Status of delegated harvesting

### ISSUE THREAD

**Issue by fyahfox** [NewEconomyMovement/NEMiOSApp#98]
0.1.31

Status of delegated harvesting is not correct.

Example for an account where delegated harvesting is unlocked (we also call it "activated" but I don't like that term, because it can be confused with "started"):
http://bob.nem.ninja:8765/#/search/TCH57Q-KL4MZA-7IDINW-LDW7DV-MASG3V-OD2F33-66E7

The app says "locked" though:

![photo_2016-01-27_01-49-58](https://cloud.githubusercontent.com/assets/6625264/12600248/66d5ff02-c498-11e5-806b-a5abc185c6b0.jpg)

**Comment by jabo38** [comment]
I have an account TA66MVNSS55QQPS4GUUDNLZJJHLYTTEYS5CIFP26

The delegated harvesting account is TAAD4F-YUOYNX-AXCYBV-5ZDBUD-X4GS2Q-SVAG2K-RLPK

You can see them linked here on Bob. http://bob.nem.ninja:8765/#/search/TA66MVNSS55QQPS4GUUDNLZJJHLYTTEYS5CIFP26

but app says delegated harvesting is locked.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 16

**Comment by jabo38** [comment]
fixed
